Incipient snapshot mechanism
dusk-network/hatchery pull request #25
Opened 2022-08-04 11:41 UTC by miloszm

Incipient snapshot mechanism - contains API for uncompressed and compressed memory snapshots including taking the snapshots as well as deploying modules off the snapshots.
Relevant test is contained in boxen.rs.

2022-08-04 11:59 UTC, krl requested changes
Just some high-level observations and change requests.

2022-08-04 11:59 UTC, krl commented on hatchery/tests/boxen.rs
> +    let id = world.deploy_from_uncompressed_snapshot(
This is way too much API surface area, the user should not have to worry about different kinds of snapshots. Either we have compression active at all times, or we don't use it.

2022-08-04 11:59 UTC, krl commented on hatchery/tests/stacked.rs
> +    let second_id = second_world.deploy(module_bytecode!("stack"))?;
Persisted worlds should include already deployed snapshots, and not have to re-deploy them.

2022-08-25 09:03 UTC, miloszm commented
superseded by PR 37

2022-08-25 09:03 UTC, closed without merging